### ISSUE TITLE
failed to compile against Qt 4.8

### ISSUE THREAD

**Issue by aol-nnov** [sk-jame/debCreator#1]
```
deb_widgets/ControlSettingsWidget.cpp:57:43: error: ‘class QComboBox’ has no member named ‘setCurrentText’
```
AFAIK, QComboBox::setCurrentText() was marked as deprecated since long time ago.

**Comment by aol-nnov** [comment]
It's a dead end, man. And here is why: https://habrahabr.ru/post/318594/#comment_9986542
source deb is the central point of any debian package.
Not interested any more.
Sorry, bye.

**Comment by sk-jame** [comment]
I don't need to build source packages. I will fix that info in my post. Building only binary packages.
http://doc.qt.io/qt-5/qcombobox.html 
deprecated? 4.8 - almost dead (for me).
